version: 2.1
orbs:
  lambda-tunnel: lambdatest/lambda-tunnel@1.0.5


parameters:
  lambdatest_email:
        description: Specify your LambdaTest email
        type: string
        default: "dhanu.devops9907@gmail.com"
  lambdatest_key:
        description: Specify environment var holding LambdaTest Access Key
        type: string
        default: "Rzh6Gt65tlWUzxdpP8lyOppCtKqfhZQezv57ibO8j1MMJ2Pyng"
  # docker:
  #     type: string
  #     default: ""


commands:
  install-tunnel-binary:
    steps:
      - run: 
          name: "Download and Extract tunnel binary"
          command: |
            wget http://downloads.lambdatest.com/tunnel/linux/64bit/LT_Linux.zip
            sudo apt-get install unzip
            unzip LT_Linux.zip
            rm LT_Linux.zip
            chmod +x LT

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - install-tunnel-binary
      
      - run:
           name: "Executing tunnel binary"
           background: true
           command: |
            #  ./LT -user ${LAMBDATEST_EMAIL} -key ${LAMBDATEST_KEY}
             ./LT  --user dhanu.devops9907@gmail.com --key Rzh6Gt65tlWUzxdpP8lyOppCtKqfhZQezv57ibO8j1MMJ2Pyng
             sleep 40

      - run: 
          name: "Setup custom environment variables"
          command: |
            echo 'export LT_USERNAME="${LAMBDATEST_USERNAME}"' >> $BASH_ENV
            echo 'export LT_ACCESS_KEY="${LAMBDATEST_ACCESS_KEY}"' >> $BASH_ENV

      - run: # test what branch we're on.
          name: "Here is the LT_Username : "
          command: echo ${LT_USERNAME}

      - run: npm install
      
      - run: node_modules/.bin/nightwatch -e chrome 
workflows:
  browser-test:
    jobs:
      - build 